### ISSUE TITLE
hideUsers.plugin.js : users are unhide when scrolling into the member list

### ISSUE THREAD

**Issue by GuegueDev** [Arashiryuu/crap#7]
Hi,
First of all, thanks for your work.

As the title says, when I scroll down and scroll up again into the member list, the one on the right part of discord ui, the hidden users are unhide. I must close the member list with the button on the top and open it again (with the same button) to hide the hidden users again.

Maybe there is an event to catch to keep them hidden ?

Thanks in advance
Guegue

**Comment by Arashiryuu** [comment]
Thanks for reporting this and for enjoying the plugin. I've pushed an update which should fix this issue.

**Comment by GuegueDev** [comment]
Hi, I'm sorry but the problem came back today despite version 1.4 :/

**Comment by Arashiryuu** [comment]
Version is now 1.6, should be resolved.
